### ISSUE TITLE
No documentation

### ISSUE THREAD

**Issue by mateuszjarzewski** [eyecatchup/php-yt_downloader#17]
Ive got no clue how to use this crapware...
Reading code is not helpful either.

```
public function download_video($c=NULL)
{
    $c = ($c !== NULL) ? $c : 0;
```

FUCK YOU!!!!

**Comment by mrzed** [comment]
So helpful. Your mother must be really proud. Perhaps you could try acting like a big boy and explain what the issue is to see if there is help instead of acting like a spoiled little whiny twat. 

---- mateuszjarzewski wrote ----

**Comment by mateuszjarzewski** [comment]
And your mother must be really slut.

The issue is: That kind of code is considered "retarded". Single letter argument variable name in main method, accompanied by lack of inline doc... You must be microcephaly. Please go kill yourself.

**Comment by eyecatchup** [comment]
@deteled
